imie_produit:
    resource: "@ImieProduitBundle/Resources/config/routing.yml"
    prefix:   /
  

login:
    pattern:   /login
    defaults:  { _controller: ImieUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout