<?php

namespace Imie\ProduitBundle\Repository;

use Doctrine\ORM\EntityRepository;

//Avec le use qui va avec :	
use Doctrine\ORM\EntityManager;
use Imie\ProduitBundle\Entity\Produit;
use Imie\ProduitBundle\Entity\Stock;
use Imie\ProduitBundle\Entity\Image;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    /* Créez une méthode getArticles() dans ArticleRepository qui vous permettra de sélectionner
les articles du plus récent au plus ancien. */
    public function  getProduits(EntityManager $em){

        $queryBuilder = $em->createQueryBuilder();
    }
}