<?php

namespace amael\blogBundle\Repository;

use Doctrine\ORM\EntityRepository;

//Avec le use qui va avec :	
use Doctrine\ORM\EntityManager;
use amael\blogBundle\Entity\Produit;
use amael\blogBundle\Entity\Stock;
use amael\blogBundle\Entity\Image;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    /* Créez une méthode getArticles() dans ArticleRepository qui vous permettra de sélectionner
les articles du plus récent au plus ancien. */
    public function  getStocks(EntityManager $em){

        $queryBuilder = $em->createQueryBuilder();
    }
}